"""Database tables for the auth layer.

The assignment asks that the local user record — not the identity provider —
be the system of record that later entities attach to. Week 3's notes will
carry an owner_id foreign key onto `users.id`, so that column has to be ours
and has to be stable.
"""

from datetime import datetime

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base so metadata.create_all() sees every table."""


class User(Base):
    """A person who has logged in through Google at least once.

    Stores identity, never credentials: with the authorization code flow this
    application never receives a password, and it does not keep Google's access
    or refresh tokens either. Nothing in Week 2 needs to call Google on the
    user's behalf after login, and a token that is not stored cannot leak from
    this table.
    """

    __tablename__ = "users"

    # Local primary key. Other tables reference this, not the Google subject,
    # so the schema does not break if the project ever adds a second provider.
    id: Mapped[int] = mapped_column(primary_key=True)

    # OIDC "sub": the identifier Google guarantees is stable and unique for
    # this account within this client. The email is deliberately *not* the key
    # — a user can change their address, and a released address can be reused.
    google_sub: Mapped[str] = mapped_column(String(255), unique=True, index=True)

    # Nullable because scopes and account settings decide whether these arrive
    # in the id_token. The login must not fail because a profile field is absent.
    email: Mapped[str | None] = mapped_column(String(320))
    name: Mapped[str | None] = mapped_column(String(255))

    # Timestamps are generated by PostgreSQL rather than by the application, so
    # every row is stamped by one clock.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<User id={self.id} google_sub={self.google_sub!r}>"
